-- PixiFinanzas — esquema inicial (D1 / SQLite)

CREATE TABLE CAT_CATEGORIA (
  ID_CATEGORIA INTEGER PRIMARY KEY,
  ETIQUETA TEXT NOT NULL,
  ACTIVO INTEGER NOT NULL DEFAULT 1,
  ORDEN INTEGER NOT NULL
);

CREATE TABLE CAT_TARJETA (
  ID_TARJETA INTEGER PRIMARY KEY,
  ETIQUETA TEXT NOT NULL,
  ACTIVO INTEGER NOT NULL DEFAULT 1,
  ORDEN INTEGER NOT NULL
);

CREATE TABLE CAT_CUENTA (
  ID_CUENTA INTEGER PRIMARY KEY,
  ETIQUETA TEXT NOT NULL,
  ACTIVO INTEGER NOT NULL DEFAULT 1,
  ORDEN INTEGER NOT NULL
);

CREATE TABLE CAT_TIPO_GASTO (
  ID_TIPO_GASTO INTEGER PRIMARY KEY,
  ETIQUETA TEXT NOT NULL,
  ACTIVO INTEGER NOT NULL DEFAULT 1,
  ORDEN INTEGER NOT NULL
);

CREATE TABLE CAT_CANAL (
  ID_CANAL INTEGER PRIMARY KEY,
  ETIQUETA TEXT NOT NULL,
  ACTIVO INTEGER NOT NULL DEFAULT 1,
  ORDEN INTEGER NOT NULL
);

CREATE TABLE CAT_MES (
  ID_MES INTEGER PRIMARY KEY, -- AAAAMM
  ETIQUETA TEXT NOT NULL,
  ANO INTEGER NOT NULL,
  MES_NUM INTEGER NOT NULL,
  ACTIVO INTEGER NOT NULL DEFAULT 1
);

-- Nombre único (unifica CAT_COTIZACION_DOLAR / CAT_COTIZACION_USD del handoff)
CREATE TABLE CAT_COTIZACION_USD (
  ID_MES INTEGER PRIMARY KEY REFERENCES CAT_MES(ID_MES),
  FECHA_COTIZACION_1ER_DIA_HABIL TEXT NOT NULL,
  VALOR_VENTA_ARS REAL NOT NULL
);

CREATE TABLE CAT_INGRESOS (
  ID_INGRESO INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_MES_ABONO INTEGER NOT NULL REFERENCES CAT_MES(ID_MES),
  IMPORTE REAL NOT NULL
);

-- ID_COMPRA agrupa las N cuotas replicadas de una misma compra (pendiente del modelo, resuelto acá).
CREATE TABLE GASTOS_TARJETA (
  ID_GASTO INTEGER PRIMARY KEY AUTOINCREMENT,
  FECHA_CARGA TEXT NOT NULL,
  DETALLE TEXT NOT NULL,
  ID_CATEGORIA INTEGER NOT NULL REFERENCES CAT_CATEGORIA(ID_CATEGORIA),
  ID_TARJETA INTEGER NOT NULL REFERENCES CAT_TARJETA(ID_TARJETA),
  ID_TIPO_GASTO INTEGER NOT NULL REFERENCES CAT_TIPO_GASTO(ID_TIPO_GASTO),
  ID_CANAL INTEGER NOT NULL REFERENCES CAT_CANAL(ID_CANAL),
  ID_MES_ABONO INTEGER NOT NULL REFERENCES CAT_MES(ID_MES),
  IMPORTE REAL NOT NULL,
  MONEDA TEXT NOT NULL DEFAULT 'ARS',
  IMPORTE_USD REAL NOT NULL,
  ID_COMPRA TEXT
);

CREATE TABLE GASTOS_TRANSFERENCIA (
  ID_GASTO INTEGER PRIMARY KEY AUTOINCREMENT,
  FECHA_CARGA TEXT NOT NULL,
  DETALLE TEXT NOT NULL,
  ID_CATEGORIA INTEGER NOT NULL REFERENCES CAT_CATEGORIA(ID_CATEGORIA),
  ID_CUENTA INTEGER NOT NULL REFERENCES CAT_CUENTA(ID_CUENTA),
  ID_TIPO_GASTO INTEGER NOT NULL REFERENCES CAT_TIPO_GASTO(ID_TIPO_GASTO),
  ID_CANAL INTEGER NOT NULL REFERENCES CAT_CANAL(ID_CANAL),
  ID_MES_ABONO INTEGER NOT NULL REFERENCES CAT_MES(ID_MES),
  IMPORTE REAL NOT NULL,
  MONEDA TEXT NOT NULL DEFAULT 'ARS',
  IMPORTE_USD REAL NOT NULL
);

CREATE INDEX idx_gt_mes ON GASTOS_TARJETA(ID_MES_ABONO);
CREATE INDEX idx_gtr_mes ON GASTOS_TRANSFERENCIA(ID_MES_ABONO);

-- Vistas desnormalizadas — todos los reportes leen de acá, nunca de las tablas base.
CREATE VIEW VISTA_GASTOS_TARJETA AS
SELECT
  g.ID_GASTO, g.FECHA_CARGA, g.DETALLE,
  c.ETIQUETA AS CATEGORIA, t.ETIQUETA AS TARJETA, tg.ETIQUETA AS TIPO_GASTO, ca.ETIQUETA AS CANAL,
  g.ID_MES_ABONO AS MES_ABONO, g.IMPORTE, g.MONEDA, g.IMPORTE_USD, g.ID_COMPRA,
  g.ID_CATEGORIA, g.ID_TARJETA, g.ID_TIPO_GASTO, g.ID_CANAL
FROM GASTOS_TARJETA g
JOIN CAT_CATEGORIA c ON c.ID_CATEGORIA = g.ID_CATEGORIA
JOIN CAT_TARJETA t ON t.ID_TARJETA = g.ID_TARJETA
JOIN CAT_TIPO_GASTO tg ON tg.ID_TIPO_GASTO = g.ID_TIPO_GASTO
JOIN CAT_CANAL ca ON ca.ID_CANAL = g.ID_CANAL;

CREATE VIEW VISTA_GASTOS_TRANSFERENCIA AS
SELECT
  g.ID_GASTO, g.FECHA_CARGA, g.DETALLE,
  c.ETIQUETA AS CATEGORIA, cu.ETIQUETA AS CUENTA, tg.ETIQUETA AS TIPO_GASTO, ca.ETIQUETA AS CANAL,
  g.ID_MES_ABONO AS MES_ABONO, g.IMPORTE, g.MONEDA, g.IMPORTE_USD,
  g.ID_CATEGORIA, g.ID_CUENTA, g.ID_TIPO_GASTO, g.ID_CANAL
FROM GASTOS_TRANSFERENCIA g
JOIN CAT_CATEGORIA c ON c.ID_CATEGORIA = g.ID_CATEGORIA
JOIN CAT_CUENTA cu ON cu.ID_CUENTA = g.ID_CUENTA
JOIN CAT_TIPO_GASTO tg ON tg.ID_TIPO_GASTO = g.ID_TIPO_GASTO
JOIN CAT_CANAL ca ON ca.ID_CANAL = g.ID_CANAL;

-- Personas, usuarios, roles y permisos
CREATE TABLE PERSONAS (
  ID_PERSONA INTEGER PRIMARY KEY AUTOINCREMENT,
  NOMBRE TEXT NOT NULL,
  APELLIDO TEXT NOT NULL,
  DNI TEXT NOT NULL UNIQUE
);

CREATE TABLE USUARIOS (
  ID_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_PERSONA INTEGER NOT NULL REFERENCES PERSONAS(ID_PERSONA),
  USUARIO TEXT NOT NULL UNIQUE,
  CLAVE_HASH TEXT NOT NULL,
  CLAVE_SALT TEXT NOT NULL,
  ROL TEXT NOT NULL CHECK (ROL IN ('Rolemaster','Consulta')),
  HABILITADO INTEGER NOT NULL DEFAULT 1
);

-- Historial de actualizaciones retroactivas masivas
CREATE TABLE HISTORIAL_ACTUALIZACIONES (
  ID_HISTORIAL INTEGER PRIMARY KEY AUTOINCREMENT,
  FECHA TEXT NOT NULL,
  USUARIO TEXT NOT NULL,
  MOTIVO TEXT NOT NULL,
  REGISTROS INTEGER NOT NULL,
  ESTADO TEXT NOT NULL CHECK (ESTADO IN ('exitoso','error')),
  DETALLE TEXT
);
