-- GENERATED by scripts/build-seed.mjs — usuario inicial (Especificaciones_Funcionales.md §8)
DELETE FROM USUARIOS;
DELETE FROM PERSONAS;
INSERT INTO PERSONAS (ID_PERSONA, NOMBRE, APELLIDO, DNI) VALUES (1, 'Lisandro', 'Giancarelli', '36444773');
INSERT INTO USUARIOS (ID_USUARIO, ID_PERSONA, USUARIO, CLAVE_HASH, CLAVE_SALT, ROL, HABILITADO)
VALUES (1, 1, 'lgiancare', 'GBRb3F92c7Ij6KJFI52x1uFnl/zNqnari8HL2fabO5Q=', 'y8V+k3xYmxwg3eRut1JvXA==', 'Rolemaster', 1);
