// Parses uploads/Gastos_modelo_v3.md (the design-session data model) into
// migrations/0002_seed.sql — a one-off ETL, per README-handoff.md section 1
// ("Ingesta inicial"). Also seeds the initial Rolemaster user from
// Especificaciones_Funcionales.md section "Identidad del primer usuario".
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const mdPath = join(root, '..', 'project', 'uploads', 'Gastos_modelo_v3.md');
const md = readFileSync(mdPath, 'utf-8');

function parseTables(text) {
  const tables = {};
  const parts = text.split(/^## (.+)$/m);
  for (let i = 1; i < parts.length; i += 2) {
    const name = parts[i].trim();
    const body = parts[i + 1];
    const lines = body.split('\n').filter((l) => l.trim().startsWith('|'));
    if (lines.length < 2) continue;
    const header = lines[0]
      .split('|').slice(1, -1)
      .map((h) => h.replace(/\\_/g, '_').trim());
    const rows = lines.slice(2).map((l) =>
      l.split('|').slice(1, -1).map((c) => c.trim())
    );
    tables[name] = { header, rows };
  }
  return tables;
}

const tables = parseTables(md);

function sqlStr(v) {
  return `'${String(v).replace(/'/g, "''")}'`;
}
function sqlBool(v) {
  return /^true$/i.test(v) ? 1 : 0;
}
function col(header, name) {
  return header.indexOf(name);
}

const out = [];
out.push('-- GENERATED by scripts/build-seed.mjs from uploads/Gastos_modelo_v3.md — do not hand-edit.\n');

function insertCatalog(tableName, cols) {
  const t = tables[tableName];
  if (!t) throw new Error(`missing table ${tableName} in source md`);
  const idx = cols.map((c) => col(t.header, c));
  out.push(`DELETE FROM ${tableName};`);
  for (const row of t.rows) {
    const vals = cols.map((c, i) => {
      const raw = row[idx[i]];
      if (/^ID_|^ANO$|^MES_NUM$|^ORDEN$/.test(c)) return raw;
      if (c === 'ACTIVO') return sqlBool(raw);
      return sqlStr(raw);
    });
    out.push(`INSERT INTO ${tableName} (${cols.join(',')}) VALUES (${vals.join(',')});`);
  }
}

insertCatalog('CAT_CATEGORIA', ['ID_CATEGORIA', 'ETIQUETA', 'ACTIVO', 'ORDEN']);
insertCatalog('CAT_TARJETA', ['ID_TARJETA', 'ETIQUETA', 'ACTIVO', 'ORDEN']);
insertCatalog('CAT_CUENTA', ['ID_CUENTA', 'ETIQUETA', 'ACTIVO', 'ORDEN']);
insertCatalog('CAT_TIPO_GASTO', ['ID_TIPO_GASTO', 'ETIQUETA', 'ACTIVO', 'ORDEN']);
insertCatalog('CAT_CANAL', ['ID_CANAL', 'ETIQUETA', 'ACTIVO', 'ORDEN']);
insertCatalog('CAT_MES', ['ID_MES', 'ETIQUETA', 'ANO', 'MES_NUM', 'ACTIVO']);
insertCatalog('CAT_COTIZACION_USD', ['ID_MES', 'FECHA_COTIZACION_1ER_DIA_HABIL', 'VALOR_VENTA_ARS']);
insertCatalog('CAT_INGRESOS', ['ID_MES_ABONO', 'IMPORTE']);

// A handful of GASTOS_TRANSFERENCIA rows in the source ship with 'NaN' for
// ID_CATEGORIA/ID_CUENTA (recurring debits the design session never finished
// categorizing). Since this is representative/fake seed data, not real
// transactions, fill the gap with a reasonable category/account instead of
// letting an unquoted 'NaN' corrupt the generated SQL.
const NAN_CATEGORIA_BY_DETALLE = {
  'Spotify': 4, // Suscripciones
  'Celular (Personal)': 10, // Operacion
  'Gym': 6, // Salud y Estilo
  'Carucha': 7, // Ajenos
  'Caja Dpto': 9, // Hogar
  'Caja Personal': 8, // Otros
  'Varios': 8, // Otros
};
const NAN_FALLBACK_ID = 1; // ID_TARJETA/ID_CUENTA fallback when the source has no value

function insertGastos(tableName, extraCols) {
  const t = tables[tableName];
  const cols = ['FECHA_CARGA', 'DETALLE', 'ID_CATEGORIA', extraCols, 'ID_TIPO_GASTO', 'ID_CANAL', 'ID_MES_ABONO', 'IMPORTE', 'MONEDA', 'IMPORTE_USD'];
  const idx = cols.map((c) => col(t.header, c));
  out.push(`DELETE FROM ${tableName};`);
  const chunks = [];
  for (const row of t.rows) {
    const detalle = row[idx[1]];
    const vals = cols.map((c, i) => {
      const raw = row[idx[i]];
      if (c === 'DETALLE' || c === 'MONEDA' || c === 'FECHA_CARGA') return sqlStr(raw);
      if (raw === 'NaN') {
        if (c === 'ID_CATEGORIA') return NAN_CATEGORIA_BY_DETALLE[detalle.trim()] ?? 8;
        return NAN_FALLBACK_ID; // ID_TARJETA / ID_CUENTA
      }
      return raw;
    });
    chunks.push(`(${vals.join(',')})`);
  }
  const batchSize = 100;
  for (let i = 0; i < chunks.length; i += batchSize) {
    out.push(`INSERT INTO ${tableName} (${cols.join(',')}) VALUES\n  ${chunks.slice(i, i + batchSize).join(',\n  ')};`);
  }
}

insertGastos('GASTOS_TARJETA', 'ID_TARJETA');
insertGastos('GASTOS_TRANSFERENCIA', 'ID_CUENTA');

writeFileSync(join(root, 'migrations', '0002_seed_catalogos_gastos.sql'), out.join('\n') + '\n');

// ── Usuario inicial ──────────────────────────────────────────────────────
const ITERATIONS = 100_000;
async function hashPassword(password) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const keyMaterial = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt, iterations: ITERATIONS, hash: 'SHA-256' }, keyMaterial, 256);
  const toB64 = (bytes) => Buffer.from(bytes).toString('base64');
  return { hash: toB64(new Uint8Array(bits)), salt: toB64(salt) };
}

const { hash, salt } = await hashPassword('Li$aClo91');
const userSql = `-- GENERATED by scripts/build-seed.mjs — usuario inicial (Especificaciones_Funcionales.md §8)
DELETE FROM USUARIOS;
DELETE FROM PERSONAS;
INSERT INTO PERSONAS (ID_PERSONA, NOMBRE, APELLIDO, DNI) VALUES (1, 'Lisandro', 'Giancarelli', '36444773');
INSERT INTO USUARIOS (ID_USUARIO, ID_PERSONA, USUARIO, CLAVE_HASH, CLAVE_SALT, ROL, HABILITADO)
VALUES (1, 1, 'lgiancare', '${hash}', '${salt}', 'Rolemaster', 1);
`;
writeFileSync(join(root, 'migrations', '0003_seed_usuario_inicial.sql'), userSql);

console.log('Seed SQL written: migrations/0002_seed_catalogos_gastos.sql, migrations/0003_seed_usuario_inicial.sql');
console.log('Rows:', Object.fromEntries(Object.entries(tables).map(([k, v]) => [k, v.rows.length])));
